### ISSUE TITLE
Does Google 1.3.6 SDK break AppengineJS?

### ISSUE THREAD

**Issue by giacecco** [gmosx/appengine_js#3]
I've lightheartedly upgraded the Google SDK to 1.3.6 and my AppengineJS website stopped working. I should have waited. The error message is below. I also upgraded to the latest Ringo and AppengineJS, but the problem is still there. In case you wondered, ringo.jar is in its right place, replacing the older one. Hope this is useful.

G. 

HTTP ERROR 500

Problem accessing /. Reason:

```
Wrapped java.io.IOException: Resource "ringo/utils/object" not found or not readable (google/appengine/ext/db/model.js#5)
```

Caused by:

org.mozilla.javascript.WrappedException: Wrapped java.io.IOException: Resource "ringo/utils/object" not found or not readable (google/appengine/ext/db/model.js#5)
    at org.ringojs.engine.RingoGlobal.require(RingoGlobal.java:129)
    at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.appengine.tools.development.agent.runtime.Runtime.invoke(Runtime.java:100)
    at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:161)
    at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:413)
    at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1711)
    at script(google/appengine/ext/db/model.js:5)
    at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:854)
    at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:178)
    at org.ringojs.engine.ReloadableScript.exec(ReloadableScript.java:294)
    at org.ringojs.engine.ReloadableScript.load(ReloadableScript.java:258)
    at org.ringojs.engine.RhinoEngine.loadModule(RhinoEngine.java:501)
    at org.ringojs.engine.RingoGlobal.require(RingoGlobal.java:126)
    at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.appengine.tools.development.agent.runtime.Runtime.invoke(Runtime.java:100)
    at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:161)
    at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:413)
    at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1711)
    at script(google/appengine/ext/db.js:30)
    at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:854)
    at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:178)
    at org.ringojs.engine.ReloadableScript.exec(ReloadableScript.java:294)
    at org.ringojs.engine.ReloadableScript.load(ReloadableScript.java:258)
    at org.ringojs.engine.RhinoEngine.loadModule(RhinoEngine.java:501)
    at org.ringojs.engine.RingoGlobal.require(RingoGlobal.java:126)
    at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.appengine.tools.development.agent.runtime.Runtime.invoke(Runtime.java:100)
    at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:161)
    at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:413)
    at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1711)
    at script(no_jour_urlShortener.js:19)
    at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:854)
    at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:178)
    at org.ringojs.engine.ReloadableScript.exec(ReloadableScript.java:294)
    at org.ringojs.engine.ReloadableScript.load(ReloadableScript.java:258)
    at org.ringojs.engine.RhinoEngine.loadModule(RhinoEngine.java:501)
    at org.ringojs.engine.RingoGlobal.require(RingoGlobal.java:126)
    at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.appengine.tools.development.agent.runtime.Runtime.invoke(Runtime.java:100)
    at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:161)
    at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:413)
    at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1711)
    at script(main.js:1)
    at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:854)
    at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:178)
    at org.ringojs.engine.ReloadableScript.exec(ReloadableScript.java:294)
    at org.ringojs.engine.ReloadableScript.load(ReloadableScript.java:258)
    at org.ringojs.engine.RhinoEngine.loadModule(RhinoEngine.java:501)
    at org.ringojs.engine.RingoGlobal.require(RingoGlobal.java:126)
    at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.appengine.tools.development.agent.runtime.Runtime.invoke(Runtime.java:100)
    at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:161)
    at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:413)
    at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1711)
    at script.handleRequest(ringo/jsgi.js:24)
    at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:854)
    at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:164)
    at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:426)
    at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3161)
    at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:162)
    at org.ringojs.engine.RhinoEngine.invoke(RhinoEngine.java:255)
    at org.ringojs.jsgi.JsgiServlet.service(JsgiServlet.java:127)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:806)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at com.google.appengine.api.blobstore.dev.ServeBlobFilter.doFilter(ServeBlobFilter.java:58)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.appengine.tools.development.StaticFileFilter.doFilter(StaticFileFilter.java:122)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at com.google.apphosting.utils.jetty.DevAppEngineWebAppContext.handle(DevAppEngineWebAppContext.java:70)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at com.google.appengine.tools.development.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:349)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
Caused by: java.io.IOException: Resource "ringo/utils/object" not found or not readable
    at org.ringojs.engine.ReloadableScript.getScript(ReloadableScript.java:111)
    at org.ringojs.engine.ReloadableScript.load(ReloadableScript.java:258)
    at org.ringojs.engine.RhinoEngine.loadModule(RhinoEngine.java:501)
    at org.ringojs.engine.RingoGlobal.require(RingoGlobal.java:126)
    ... 92 more
Caused by:

java.io.IOException: Resource "ringo/utils/object" not found or not readable
    at org.ringojs.engine.ReloadableScript.getScript(ReloadableScript.java:111)
    at org.ringojs.engine.ReloadableScript.load(ReloadableScript.java:258)
    at org.ringojs.engine.RhinoEngine.loadModule(RhinoEngine.java:501)
    at org.ringojs.engine.RingoGlobal.require(RingoGlobal.java:126)
    at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.appengine.tools.development.agent.runtime.Runtime.invoke(Runtime.java:100)
    at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:161)
    at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:413)
    at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1711)
    at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:854)
    at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:178)
    at org.ringojs.engine.ReloadableScript.exec(ReloadableScript.java:294)
    at org.ringojs.engine.ReloadableScript.load(ReloadableScript.java:258)
    at org.ringojs.engine.RhinoEngine.loadModule(RhinoEngine.java:501)
    at org.ringojs.engine.RingoGlobal.require(RingoGlobal.java:126)
    at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.appengine.tools.development.agent.runtime.Runtime.invoke(Runtime.java:100)
    at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:161)
    at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:413)
    at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1711)
    at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:854)
    at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:178)
    at org.ringojs.engine.ReloadableScript.exec(ReloadableScript.java:294)
    at org.ringojs.engine.ReloadableScript.load(ReloadableScript.java:258)
    at org.ringojs.engine.RhinoEngine.loadModule(RhinoEngine.java:501)
    at org.ringojs.engine.RingoGlobal.require(RingoGlobal.java:126)
    at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.appengine.tools.development.agent.runtime.Runtime.invoke(Runtime.java:100)
    at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:161)
    at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:413)
    at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1711)
    at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:854)
    at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:178)
    at org.ringojs.engine.ReloadableScript.exec(ReloadableScript.java:294)
    at org.ringojs.engine.ReloadableScript.load(ReloadableScript.java:258)
    at org.ringojs.engine.RhinoEngine.loadModule(RhinoEngine.java:501)
    at org.ringojs.engine.RingoGlobal.require(RingoGlobal.java:126)
    at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.appengine.tools.development.agent.runtime.Runtime.invoke(Runtime.java:100)
    at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:161)
    at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:413)
    at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1711)
    at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:854)
    at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:178)
    at org.ringojs.engine.ReloadableScript.exec(ReloadableScript.java:294)
    at org.ringojs.engine.ReloadableScript.load(ReloadableScript.java:258)
    at org.ringojs.engine.RhinoEngine.loadModule(RhinoEngine.java:501)
    at org.ringojs.engine.RingoGlobal.require(RingoGlobal.java:126)
    at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.appengine.tools.development.agent.runtime.Runtime.invoke(Runtime.java:100)
    at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:161)
    at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:413)
    at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1711)
    at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:854)
    at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:164)
    at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:426)
    at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3161)
    at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:162)
    at org.ringojs.engine.RhinoEngine.invoke(RhinoEngine.java:255)
    at org.ringojs.jsgi.JsgiServlet.service(JsgiServlet.java:127)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:806)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at com.google.appengine.api.blobstore.dev.ServeBlobFilter.doFilter(ServeBlobFilter.java:58)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.appengine.tools.development.StaticFileFilter.doFilter(StaticFileFilter.java:122)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at com.google.apphosting.utils.jetty.DevAppEngineWebAppContext.handle(DevAppEngineWebAppContext.java:70)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at com.google.appengine.tools.development.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:349)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
Powered by Jetty://

**Comment by gmosx** [comment]
It works with 1.3.6 you just have to move app.yaml inside WEB-INF.

regarding your problem, are you sure you have the latest version of Ringo and you have run 'ant jar' ?

**Comment by giacecco** [comment]
Moved app.yaml to WEB-INF as you suggested, thanks, but that wasn't the solution to the original problem. The error I get now is identical to the original.

I have the latest Ringo from their Git repository, and done the ant jar stuff as usual.

Is it possible that for some strange reason the development server can't find Ringo any longer? Where in the application, in which .yaml or equivalent, I tell the SKD where to find the libraries I reference?

**Comment by gmosx** [comment]
the only change I needed to update to 1.3.6 was to move app.yaml inside WEB-INF. I will have another look tomorrow.

**Comment by giacecco** [comment]
Hi gmosx how did it go? Did 1.3.6 break anything to you, too?

**Comment by gmosx** [comment]
no 1.3.6 works fine for me... send me a zip of you app so that I can have a look.

**Comment by giacecco** [comment]
This was solved ages ago, sorry for keeping the issue open.
